imports:
    - { resource: ezplatform.yml }

ezpublish:
    siteaccess:
        match:
            Compound\LogicalAnd:
                movidiet:
                    matchers:
                        Map\URI:
                            fr: true
                        Map\Host:
                            movidiet.dev: true
                    match: movidiet
                movidiet_en:
                    matchers:
                        Map\URI:
                            en: true
                        Map\Host:
                            movidiet.dev: true
                    match: movidiet_en