imports:
    - { resource: ezplatform.yml }

ezpublish:
    system:
        cvwebsite:
            languages: [fre-FR]
        cvwebsite_en:
            # In site_authors_sanofi_fr siteaccess, fre-FR is always preferred, and fallback to eng-US if needed.
            languages: [eng-GB, fre-FR]
    siteaccess:
        match:
            Compound\LogicalAnd:
                cvwebsite:
                    matchers:
                        Map\URI:
                            fr: true
                        Map\Host:
                            lucasimonin.me: true
                    match: cvwebsite
                cvwebsite_en:
                    matchers:
                        Map\URI:
                            en: true
                        Map\Host:
                            lucasimonin.me: true
                    match: cvwebsite_en
            Map\Host:
                lucasimonin.me: cvwebsite