imports:
    - { resource: ezplatform.yml }

ezpublish:
    siteaccess:
        match:
            Compound\LogicalAnd:
                freelancewebsite:
                    matchers:
                        Map\URI:
                            fr: true
                        Map\Host:
                            lucasimonin.dev: true
                    match: freelancewebsite
                freelancewebsite_en:
                    matchers:
                        Map\URI:
                            en: true
                        Map\Host:
                            lucasimonin.dev: true
                    match: freelancewebsite_en