imports:
    - { resource: ezplatform.yml }

ezpublish:
    system:
        freelancewebsite:
            languages: [fre-FR]
        freelancewebsite_en:
            # In site_authors_sanofi_fr siteaccess, fre-FR is always preferred, and fallback to eng-US if needed.
            languages: [eng-GB, fre-FR]
    siteaccess:
        match:
            Compound\LogicalAnd:
                freelancewebsite:
                    matchers:
                        Map\URI:
                            fr: true
                        Map\Host:
                            lucasimonin.me: true
                    match: freelancewebsite
                freelancewebsite_en:
                    matchers:
                        Map\URI:
                            en: true
                        Map\Host:
                            lucasimonin.me: true
                    match: freelancewebsite_en
            Map\Host:
                lucasimonin.me: freelancewebsite