imports:
    - { resource: ezplatform.yml }

ezpublish:
    siteaccess:
        match:
            Compound\LogicalAnd:
                cvwebsite:
                    matchers:
                        Map\URI:
                            fr: true
                        Map\Host:
                            lucasimonin.dev: true
                    match: cvwebsite
                cvwebsite_en:
                    matchers:
                        Map\URI:
                            en: true
                        Map\Host:
                            lucasimonin.dev: true
                    match: cvwebsite_en