ezpublish:
    system:
        default:
            image_variations:
                article_image:
                    reference: ~
                    filters:
                        - { name: geometry/scaleheight, params: [180] }