services:
    app.core_helper:
             class: App\Bundle\SiteBundle\Helper\CoreHelper
             arguments: ["@ezpublish.api.repository", "@app.criteria_helper", "@logger"]
    app.criteria_helper:
            class: App\Bundle\SiteBundle\Helper\CriteriaHelper
