services:
    app.core_helper:
             class: %app.core_helper.class%
             arguments: ["@ezpublish.api.repository", "@app.criteria_helper", "@logger"]
    app.criteria_helper:
            class: %app.criteria_helper.class%
            arguments: ["@ezpublish.siteaccess"]
    app.form.type.contact:
            class: %app.form.type.contact.class%
            arguments: ["@service_container"]
            tags:
                - { name: form.type, alias: contact_type }