parameters:
    app.blog.locationid: 63
    app.formules.locationid: 64
    app.blog.article.limit: 5
    app.article.content_type.identifier: article
    app.formule.content_type.identifier: formule
    app.article.category.sport: 0
    app.article.category.diet: 1
    app.article.category.recipe: 2