parameters:
    app.blog.locationid: 63
    app.formules.locationid: 64
    app.contacts.locationid: 72
    app.works.locationid: 76
    app.blog.article.limit: 5
    app.article.content_type.identifier: article
    app.formule.content_type.identifier: formule
    app.contact.content_type.identifier: contact
    app.work.content_type.identifier: work
    app.cache.high.ttl: 3600